### ISSUE TITLE
Linux version freezes while editing joystick controls

### ISSUE THREAD

**Issue by SilverLatios** [TASVideos/desmume#430]
System: Ubuntu 20.10
CPU: i7-9750h
Graphics Card: gtx1660ti
Controller: Xbox Series controller
Version: latest version compiled with meson.
Symptom: The entire application have stopped responding while editing joystick controls.
Additional information: the application have stopped responding even before I was able to make any input. The apt-get version did not have this issue however.

**Comment by thesourcehim** [comment]
@linkmauve 
I did some tests, played around with GTK event loop, added main loop processing between iterations inside get_joy_key. Strangely when get_joy_key is called for the first time, it detects pressed button after a couple of seconds. But subsequent calls to button config dialog and get_joy_key results in infinite wait loop (i.e. no new SDL events are coming despite buttons being pressed).

Here's some code I used for test:

```
/* Get pressed joystick key while processing other events (don't block gui)*/
u16 get_wait_joy_key(int index, void (*pwaitproc)()) {
  BOOL done = FALSE;
  SDL_Event event;
  u16 key = joypad_cfg[index];

  /* Enable joystick events if needed */
  if( SDL_JoystickEventState(SDL_QUERY) == SDL_IGNORE )
    SDL_JoystickEventState(SDL_ENABLE);

  while(!done)
    {
      SDL_PumpEvents();
	  if(SDL_PollEvent(&event))
	  {
		switch(event.type)
        {
        case SDL_JOYBUTTONDOWN:
          printf( "Device: %d; Button: %d\n", event.jbutton.which, event.jbutton.button );
          key = ((event.jbutton.which & 15) << 12) | JOY_BUTTON << 8 | (event.jbutton.button & 255);
          done = TRUE;
          break;
        case SDL_JOYAXISMOTION:
          /* Dead zone of 50% */
          if( ((u32)abs(event.jaxis.value) >> 14) != 0 )
            {
              key = ((event.jaxis.which & 15) << 12) | JOY_AXIS << 8 | ((event.jaxis.axis & 127) << 1);
              if (event.jaxis.value > 0) {
                printf( "Device: %d; Axis: %d (+)\n", event.jaxis.which, event.jaxis.axis );
                key |= 1;
              }
              else
                printf( "Device: %d; Axis: %d (-)\n", event.jaxis.which, event.jaxis.axis );
              done = TRUE;
            }
          break;
        case SDL_JOYHATMOTION:
          /* Diagonal positions will be treated as two separate keys being activated, rather than a single diagonal key. */
          /* JOY_HAT_* are sequential integers, rather than a bitmask */
          if (event.jhat.value != SDL_HAT_CENTERED) {
            key = ((event.jhat.which & 15) << 12) | JOY_HAT << 8 | ((event.jhat.hat & 63) << 2);
            /* Can't just use a switch here because SDL_HAT_* make up a bitmask. We only want one of these when assigning keys. */
            if ((event.jhat.value & SDL_HAT_UP) != 0) {
              key |= JOY_HAT_UP;
              printf( "Device: %d; Hat: %d (Up)\n", event.jhat.which, event.jhat.hat );
            }
            else if ((event.jhat.value & SDL_HAT_RIGHT) != 0) {
              key |= JOY_HAT_RIGHT;
              printf( "Device: %d; Hat: %d (Right)\n", event.jhat.which, event.jhat.hat );
            }
            else if ((event.jhat.value & SDL_HAT_DOWN) != 0) {
              key |= JOY_HAT_DOWN;
              printf( "Device: %d; Hat: %d (Down)\n", event.jhat.which, event.jhat.hat );
            }
            else if ((event.jhat.value & SDL_HAT_LEFT) != 0) {
              key |= JOY_HAT_LEFT;
              printf( "Device: %d; Hat: %d (Left)\n", event.jhat.which, event.jhat.hat );
            }
            done = TRUE;
          }
          break;
        }
	  }
	  else
		  pwaitproc();
    }

  if( SDL_JoystickEventState(SDL_QUERY) == SDL_ENABLE )
    SDL_JoystickEventState(SDL_IGNORE);

  return key;
}

static void ui_wait_proc()
{
	gtk_main_iteration_do(false);
}

static void AcceptNewJoyKey(GtkWidget *w, GdkEventFocus *e, struct modify_key_ctx *ctx)
{
    gchar *YouPressed;

    ctx->mk_key_chosen = get_wait_joy_key(ctx->key_id, ui_wait_proc);

    YouPressed = g_strdup_printf("You pressed : %d\nClick OK to keep this key.", ctx->mk_key_chosen);
    gtk_label_set_text(GTK_LABEL(ctx->label), YouPressed);
    g_free(YouPressed);
}
```

**Comment by thesourcehim** [comment]
Tested with newly arrived SDL2 support, no change, problem persists.

**Comment by thesourcehim** [comment]
Pull request #436 should fix the issue, works for me at least, please test.

**Comment by thesourcehim** [comment]
@linkmauve also maybe we should disallow joystick controls editing when no joysticks are connected, otherwise application still freezes since no joystick events come.

**Comment by aljohnston112** [comment]
I have this issue with the Flatpak version on Ubuntu

**Comment by thesourcehim** [comment]
'flatpack search desmume' gives 0.9.11 version for me. It's super old. You should build newer version from source.

**Comment by ladios233** [comment]
> Pull request #436 should fix the issue, works for me at least, please test.

Sorry for the late reply.
The problem still exists when compiling with the latest code. However, the program would not stop responding if there is no opened ROM; instead, the program would refuse to take any input from my controller.

**Comment by SilverLatios** [comment]
> > > Pull request #436 should fix the issue, works for me at least, please test.
> > 
> > 
> > Sorry for the late reply.
> > The problem still exists when compiling with the latest code. However, the program would not stop responding if there is no opened ROM; instead, the program would refuse to take any input from my controller.
> 
> I can't reproduce this. With or without ROM opened input from my controller is registered. Do you plug your controller before starting desmume? All game pads are initialized at start only. Also test your controller with jstest to see of it's working at all.

I have tested again with the controller plugged before desmume starts, the problem is resolved. Thank you.
